### ISSUE TITLE
Dockerでコンテナを立てる

### ISSUE THREAD

**Issue by takanori-matsushita** [takanori-matsushita/gridsome-practice#2]
WordpressとDBのDockerコンテナを立てる

**Comment by takanori-matsushita** [comment]
docker-compose.ymlファイルを作成

**Comment by takanori-matsushita** [comment]
wordpressのimageはDocker hubにあったので、それを使用した。versionはlatest（この時点で5.3.2）

**Comment by takanori-matsushita** [comment]
DBも同様にDockerのimageを使用。versionは国内レンタルサーバーを参考に、5.6にした。

**Comment by takanori-matsushita** [comment]
それぞれデータをマウントする。Wordpressは、themesの中だけファイル編集するように以下のようにした。
 
DB`./.db_data:/var/lib/mysql`
 
Wordpress `./wordpress:/var/www/html/wp-content/themes`

**Comment by takanori-matsushita** [comment]
Wordpressのポートをホスト側の8080で接続できるようにした。

**Comment by takanori-matsushita** [comment]
DBとWordpressを接続する設定をした。環境変数は.envファイルに設定し、gitignoreに.envを追記
```
**DBの設定**
environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
```
```
**Wordpressの設定**
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
```
